"use client"

import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import {useState} from 'react';
import {BsSearch} from 'react-icons/bs';
import Weather from './Weather';


export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState (false);
 
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=c67c57dabcc6ea2389957b526dd434ec`

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }

    return (
      <div>
        <Head>
          <title>Weather - Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' alt='test' />
        </Head>

        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'/>

        <Image src='https://cozcastel.fr/wp-content/gallery/coz-castel-photo/drone_mur_de_galet.jpg' 
        layout='fill'
        className='object-cover'
        />

<div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          <form
            onSubmit={fetchWeather}
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
            <div>
              <input
                onChange={(e)=> setCity(e.target.value)}
                className='bg-transparent border-none text-white focus:outline-none text-2xl'
                type='text'
                placeholder='ville'
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>

{/*weather*/}
{weather.main && <Weather data={weather}/> }
        </div>
    );
}